name: Run DLT Pipeline with FastAPI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-2' 

      - name: Run FastAPI server in background
        run: |
          uvicorn pain:app --host 127.0.0.1 --port 8000 &
          sleep 10  # Give FastAPI time to start

      - name: Run DLT pipeline
        env:
          DLT_REDSHIFT_USERNAME: ${{ secrets.REDSHIFT_USER }}
          DLT_REDSHIFT_PASSWORD: ${{ secrets.REDSHIFT_PASSWORD }}
          DLT_REDSHIFT_HOST: ${{ secrets.REDSHIFT_HOST }}
          DLT_REDSHIFT_PORT: ${{ secrets.REDSHIFT_PORT }}
          DLT_REDSHIFT_DATABASE: ${{ secrets.REDSHIFT_DB }}
          DLT_BUCKET_URL: ${{ secrets.AWS_BUCKET_URL }}
        run: python rest_api_pipeline.py
